// models tbc

function getStudentData() {}
function updateBook() {}
function newBook() {}
function noBook() {}
function completeBooks() {}
function dictionary() {}
function newWord() {}
function messages() {}
function getAllStudentsAndTeacher() {}
function getWholeClassSevenStat() {}
function getWholeClassPages() {}
function getWholeClassMinutes() {}
function getWholeClassBooksFinished() {}
function individualSevenStat() {}
function individualPages() {}
function individualMinutes() {}
function individualBooksFinished() {}
function classMessageLog() {}
function newStudentFeedback() {}
function studentMessageLog() {}
function studentSummaries() {}
function newClassFeedback() {}
